# Tested with Ansible 2.9.2 and AS3 3.17.1 (TMOS 15.1.0.1)
---
- name: LINKLIGHT AS3
  hosts: ansible_test
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['webservers'] }}"

  tasks:
  - name: CREATE AS3 JSON BODY
    set_fact:
      as3_app_body: "{{ lookup('template', '../template/as3_template.j2', split_lines=False) }}"

  - name: PUSH AS3
    uri:
      url: "https://{{ ansible_host }}/mgmt/shared/appsvcs/declare"
      method: POST
      body: "{{ lookup('template','../templates/tenant_base.j2', split_lines=False) }}"
      status_code: 200
      timeout: 300
      body_format: json
      force_basic_auth: yes
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: no
    delegate_to: localhost
...